# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reports.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Report(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1339, 825)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.b1 = QtWidgets.QProgressBar(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(130, 220, 1111, 50))
        self.b1.setStyleSheet("border: solid grey;\n"
"border-radius: 15px;\n"
"color: black; \n"
"")
        self.b1.setProperty("value", 24)
        self.b1.setObjectName("b1")
        self.r1 = QtWidgets.QLabel(self.centralwidget)
        self.r1.setGeometry(QtCore.QRect(130, 140, 321, 60))
        self.r1.setObjectName("r1")
        self.r2 = QtWidgets.QLabel(self.centralwidget)
        self.r2.setGeometry(QtCore.QRect(130, 290, 321, 60))
        self.r2.setObjectName("r2")
        self.b2 = QtWidgets.QProgressBar(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(130, 360, 1111, 50))
        self.b2.setStyleSheet("border: solid grey;\n"
"border-radius: 15px;\n"
"color: black; \n"
"")
        self.b2.setProperty("value", 24)
        self.b2.setObjectName("b2")
        self.r3 = QtWidgets.QLabel(self.centralwidget)
        self.r3.setGeometry(QtCore.QRect(130, 430, 321, 60))
        self.r3.setObjectName("r3")
        self.b3 = QtWidgets.QProgressBar(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(130, 510, 1111, 50))
        self.b3.setStyleSheet("border: solid grey;\n"
"border-radius: 15px;\n"
"color: black; \n"
"")
        self.b3.setProperty("value", 24)
        self.b3.setObjectName("b3")
        self.r4 = QtWidgets.QLabel(self.centralwidget)
        self.r4.setGeometry(QtCore.QRect(130, 580, 321, 60))
        self.r4.setObjectName("r4")
        self.b4 = QtWidgets.QProgressBar(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(130, 660, 1111, 50))
        self.b4.setStyleSheet("border: solid grey;\n"
"border-radius: 15px;\n"
"color: black; \n"
"")
        self.b4.setProperty("value", 24)
        self.b4.setObjectName("b4")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(10, 10, 1321, 81))
        self.title.setObjectName("title")
        Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1339, 22))
        self.menubar.setObjectName("menubar")
        Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form)
        self.statusbar.setObjectName("statusbar")
        Form.setStatusBar(self.statusbar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.r1.setText(_translate("Form", "Overall Well Being"))
        self.r2.setText(_translate("Form", "Functioning"))
        self.r3.setText(_translate("Form", "Problems/Symptoms"))
        self.r4.setText(_translate("Form", "Risk"))
        self.title.setText(_translate("Form", "Report Results"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QMainWindow()
    ui = Ui_Report()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
