# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1339, 825)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.Interviewer = QtWidgets.QLabel(self.centralwidget)
        self.Interviewer.setGeometry(QtCore.QRect(40, 140, 981, 611))
        self.Interviewer.setStyleSheet("")
        self.Interviewer.setText("")
        self.Interviewer.setObjectName("Interviewer")
        self.Transcript = QtWidgets.QLabel(self.centralwidget)
        self.Transcript.setGeometry(QtCore.QRect(1050, 300, 261, 341))
        self.Transcript.setStyleSheet("background-color: rgb(255, 203, 230);\n"
"padding: 2px;")
        self.Transcript.setText("")
        self.Transcript.setObjectName("Transcript")
        self.image_label = QtWidgets.QLabel(self.centralwidget)
        self.image_label.setGeometry(QtCore.QRect(1050, 140, 261, 131))
        self.image_label.setObjectName("image_label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1050, 650, 261, 131))
        self.pushButton.setStyleSheet("background-color: rgb(255, 203, 230);\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: white;")
        self.pushButton.setObjectName("pushButton")
        Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1339, 22))
        self.menubar.setObjectName("menubar")
        Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form)
        self.statusbar.setObjectName("statusbar")
        Form.setStatusBar(self.statusbar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.image_label.setText(_translate("Form", "Human Video"))
        self.pushButton.setText(_translate("Form", "Ready to Speak"))
